import { Transaction, CategoryBudget, MonthlyAnalytics, TransactionType, BudgetPeriod } from './types';

// Navigation items for dashboard sidebar
export const NAV_ITEMS = [
  { href: '/dashboard', icon: 'dashboard', label: 'Dashboard', color: 'pink' },
  { href: '/dashboard/transactions', icon: 'receipt_long', label: 'Transactions', color: 'blue' },
  { href: '/dashboard/budgets', icon: 'savings', label: 'Budget', color: 'yellow' },
  { href: '/dashboard/analytics', icon: 'bar_chart', label: 'Analytics', color: 'green' },
  { href: '/dashboard/settings', icon: 'settings', label: 'Settings', color: 'orange' },
];

// Mock data for dashboard KPIs
export const MOCK_KPIS = {
  netWorth: {
    value: 142500,
    trend: '+2.5%',
    trendUp: true,
    progress: 75,
    progressLabel: 'Net Worth Target',
  },
  totalSpent: {
    value: 3240,
    trend: '+1.2%',
    trendUp: true,
    progress: 45,
    progressLabel: 'Budget Usage',
  },
  savings: {
    value: 18,
    isPercentage: true,
    trend: 'Stable',
    trendUp: null,
    progress: 18,
    progressLabel: 'Annual Yield',
  },
};

// Mock data for cash flow chart
export const MOCK_CASH_FLOW = [
  { week: 'Week 1', income: 2500, expenses: 1200 },
  { week: 'Week 2', income: 3200, expenses: 1800 },
  { week: 'Week 3', income: 1800, expenses: 900 },
  { week: 'Week 4', income: 4200, expenses: 2100 },
];

// Mock data for recent transactions
export const MOCK_TRANSACTIONS = [
  {
    id: '1',
    merchant: 'Whole Foods Market',
    icon: 'shopping_cart',
    iconColor: 'bg-accent-blue',
    category: 'Groceries',
    date: 'Today, 2:30 PM',
    amount: -142.50,
    type: 'expense' as const,
  },
  {
    id: '2',
    merchant: 'Netflix',
    icon: 'movie',
    iconColor: 'bg-accent-yellow',
    category: 'Entertainment',
    date: 'Yesterday',
    amount: -15.99,
    type: 'expense' as const,
  },
  {
    id: '3',
    merchant: 'Tech Solutions Inc.',
    icon: 'payments',
    iconColor: 'bg-accent-green',
    category: 'Income',
    date: 'Dec 18',
    amount: 2450.00,
    type: 'income' as const,
  },
];

// Mock data for linked accounts
export const MOCK_ACCOUNTS = [
  {
    id: '1',
    name: 'Chase Checking',
    lastFour: '4582',
    balance: 5240.50,
    icon: 'account_balance',
  },
  {
    id: '2',
    name: 'Ally Savings',
    lastFour: '9921',
    balance: 32000.00,
    icon: 'savings',
  },
  {
    id: '3',
    name: 'Amex Gold',
    lastFour: '1002',
    balance: -450.25,
    icon: 'credit_card',
  },
];

// Mock data for top budgets
export const MOCK_BUDGETS = [
  {
    id: '1',
    name: 'Groceries',
    icon: 'shopping_cart',
    color: 'bg-accent-blue',
    spent: 450,
    limit: 600,
    warning: false,
  },
  {
    id: '2',
    name: 'Dining Out',
    icon: 'restaurant',
    color: 'bg-primary',
    spent: 560,
    limit: 600,
    warning: true,
  },
  {
    id: '3',
    name: 'Transport',
    icon: 'directions_car',
    color: 'bg-accent-yellow',
    spent: 120,
    limit: 200,
    warning: false,
  },
];

// ===== EXTENDED MOCK DATA FOR TRANSACTIONS, BUDGETS, AND ANALYTICS =====

// Category definitions with icons and colors
export const CATEGORIES = [
  { id: 'cat-1', name: 'Groceries', icon: 'shopping_cart', color: '#66D9EF' }, // cyan
  { id: 'cat-2', name: 'Dining Out', icon: 'restaurant', color: '#F92672' }, // pink
  { id: 'cat-3', name: 'Transportation', icon: 'directions_car', color: '#E6DB74' }, // yellow
  { id: 'cat-4', name: 'Entertainment', icon: 'movie', color: '#AE81FF' }, // purple
  { id: 'cat-5', name: 'Shopping', icon: 'shopping_bag', color: '#FD971F' }, // orange
  { id: 'cat-6', name: 'Healthcare', icon: 'local_hospital', color: '#A6E22E' }, // green
  { id: 'cat-7', name: 'Utilities', icon: 'bolt', color: '#75715E' }, // gray
  { id: 'cat-8', name: 'Salary', icon: 'payments', color: '#A6E22E' }, // green
  { id: 'cat-9', name: 'Freelance', icon: 'work', color: '#66D9EF' }, // cyan
  { id: 'cat-10', name: 'Rent', icon: 'home', color: '#F92672' }, // pink
  { id: 'cat-11', name: 'Subscriptions', icon: 'subscriptions', color: '#AE81FF' }, // purple
  { id: 'cat-12', name: 'Fitness', icon: 'fitness_center', color: '#A6E22E' }, // green
  { id: 'cat-13', name: 'Travel', icon: 'flight', color: '#66D9EF' }, // cyan
  { id: 'cat-14', name: 'Gifts', icon: 'card_giftcard', color: '#F92672' }, // pink
  { id: 'cat-15', name: 'Education', icon: 'school', color: '#E6DB74' }, // yellow
];

// Comprehensive transaction list (30 transactions)
export const TRANSACTIONS_DATA: Transaction[] = [
  // Recent transactions (last week)
  {
    id: 'txn-1',
    merchant: 'Whole Foods Market',
    icon: 'shopping_cart',
    iconColor: '#66D9EF',
    category: 'Groceries',
    categoryId: 'cat-1',
    date: '2024-01-15T14:30:00Z',
    amount: 142.50,
    type: TransactionType.Expense,
    description: 'Weekly grocery shopping',
    currency: 'USD',
  },
  {
    id: 'txn-2',
    merchant: 'Starbucks',
    icon: 'restaurant',
    iconColor: '#F92672',
    category: 'Dining Out',
    categoryId: 'cat-2',
    date: '2024-01-15T08:15:00Z',
    amount: 6.75,
    type: TransactionType.Expense,
    description: 'Morning coffee',
    currency: 'USD',
  },
  {
    id: 'txn-3',
    merchant: 'Tech Corp Inc.',
    icon: 'payments',
    iconColor: '#A6E22E',
    category: 'Salary',
    categoryId: 'cat-8',
    date: '2024-01-14T00:00:00Z',
    amount: 4500.00,
    type: TransactionType.Income,
    description: 'Bi-weekly paycheck',
    currency: 'USD',
  },
  {
    id: 'txn-4',
    merchant: 'Shell Gas Station',
    icon: 'directions_car',
    iconColor: '#E6DB74',
    category: 'Transportation',
    categoryId: 'cat-3',
    date: '2024-01-13T17:45:00Z',
    amount: 52.30,
    type: TransactionType.Expense,
    description: 'Gas fill-up',
    currency: 'USD',
  },
  {
    id: 'txn-5',
    merchant: 'Netflix',
    icon: 'subscriptions',
    iconColor: '#AE81FF',
    category: 'Subscriptions',
    categoryId: 'cat-11',
    date: '2024-01-13T00:00:00Z',
    amount: 15.99,
    type: TransactionType.Expense,
    description: 'Monthly subscription',
    currency: 'USD',
  },
  {
    id: 'txn-6',
    merchant: 'AMC Theaters',
    icon: 'movie',
    iconColor: '#AE81FF',
    category: 'Entertainment',
    categoryId: 'cat-4',
    date: '2024-01-12T19:30:00Z',
    amount: 38.50,
    type: TransactionType.Expense,
    description: 'Movie tickets and snacks',
    currency: 'USD',
  },
  {
    id: 'txn-7',
    merchant: 'Trader Joe\'s',
    icon: 'shopping_cart',
    iconColor: '#66D9EF',
    category: 'Groceries',
    categoryId: 'cat-1',
    date: '2024-01-11T16:20:00Z',
    amount: 87.40,
    type: TransactionType.Expense,
    description: 'Groceries',
    currency: 'USD',
  },
  {
    id: 'txn-8',
    merchant: 'Uber',
    icon: 'directions_car',
    iconColor: '#E6DB74',
    category: 'Transportation',
    categoryId: 'cat-3',
    date: '2024-01-11T22:15:00Z',
    amount: 24.80,
    type: TransactionType.Expense,
    description: 'Ride home',
    currency: 'USD',
  },
  {
    id: 'txn-9',
    merchant: 'Chipotle',
    icon: 'restaurant',
    iconColor: '#F92672',
    category: 'Dining Out',
    categoryId: 'cat-2',
    date: '2024-01-10T12:30:00Z',
    amount: 14.25,
    type: TransactionType.Expense,
    description: 'Lunch',
    currency: 'USD',
  },
  {
    id: 'txn-10',
    merchant: 'Amazon',
    icon: 'shopping_bag',
    iconColor: '#FD971F',
    category: 'Shopping',
    categoryId: 'cat-5',
    date: '2024-01-10T00:00:00Z',
    amount: 127.99,
    type: TransactionType.Expense,
    description: 'Home office supplies',
    currency: 'USD',
  },
  // Week 2
  {
    id: 'txn-11',
    merchant: 'LA Fitness',
    icon: 'fitness_center',
    iconColor: '#A6E22E',
    category: 'Fitness',
    categoryId: 'cat-12',
    date: '2024-01-09T00:00:00Z',
    amount: 39.99,
    type: TransactionType.Expense,
    description: 'Monthly membership',
    currency: 'USD',
  },
  {
    id: 'txn-12',
    merchant: 'PG&E',
    icon: 'bolt',
    iconColor: '#75715E',
    category: 'Utilities',
    categoryId: 'cat-7',
    date: '2024-01-08T00:00:00Z',
    amount: 142.30,
    type: TransactionType.Expense,
    description: 'Electric bill',
    currency: 'USD',
  },
  {
    id: 'txn-13',
    merchant: 'Walgreens',
    icon: 'local_hospital',
    iconColor: '#A6E22E',
    category: 'Healthcare',
    categoryId: 'cat-6',
    date: '2024-01-08T14:20:00Z',
    amount: 32.50,
    type: TransactionType.Expense,
    description: 'Prescription refill',
    currency: 'USD',
  },
  {
    id: 'txn-14',
    merchant: 'Spotify',
    icon: 'subscriptions',
    iconColor: '#AE81FF',
    category: 'Subscriptions',
    categoryId: 'cat-11',
    date: '2024-01-07T00:00:00Z',
    amount: 10.99,
    type: TransactionType.Expense,
    description: 'Premium subscription',
    currency: 'USD',
  },
  {
    id: 'txn-15',
    merchant: 'Panera Bread',
    icon: 'restaurant',
    iconColor: '#F92672',
    category: 'Dining Out',
    categoryId: 'cat-2',
    date: '2024-01-07T13:00:00Z',
    amount: 18.45,
    type: TransactionType.Expense,
    description: 'Lunch meeting',
    currency: 'USD',
  },
  {
    id: 'txn-16',
    merchant: 'Target',
    icon: 'shopping_bag',
    iconColor: '#FD971F',
    category: 'Shopping',
    categoryId: 'cat-5',
    date: '2024-01-06T15:30:00Z',
    amount: 89.99,
    type: TransactionType.Expense,
    description: 'Household items',
    currency: 'USD',
  },
  {
    id: 'txn-17',
    merchant: 'Safeway',
    icon: 'shopping_cart',
    iconColor: '#66D9EF',
    category: 'Groceries',
    categoryId: 'cat-1',
    date: '2024-01-05T17:45:00Z',
    amount: 112.80,
    type: TransactionType.Expense,
    description: 'Weekly shopping',
    currency: 'USD',
  },
  {
    id: 'txn-18',
    merchant: 'Freelance Client',
    icon: 'work',
    iconColor: '#66D9EF',
    category: 'Freelance',
    categoryId: 'cat-9',
    date: '2024-01-05T00:00:00Z',
    amount: 850.00,
    type: TransactionType.Income,
    description: 'Website project payment',
    currency: 'USD',
  },
  // Week 3
  {
    id: 'txn-19',
    merchant: 'Apple Store',
    icon: 'shopping_bag',
    iconColor: '#FD971F',
    category: 'Shopping',
    categoryId: 'cat-5',
    date: '2024-01-04T11:00:00Z',
    amount: 349.00,
    type: TransactionType.Expense,
    description: 'AirPods Pro',
    currency: 'USD',
  },
  {
    id: 'txn-20',
    merchant: 'Delta Airlines',
    icon: 'flight',
    iconColor: '#66D9EF',
    category: 'Travel',
    categoryId: 'cat-13',
    date: '2024-01-03T00:00:00Z',
    amount: 420.00,
    type: TransactionType.Expense,
    description: 'Flight to NYC',
    currency: 'USD',
  },
  {
    id: 'txn-21',
    merchant: 'Downtown Property Mgmt',
    icon: 'home',
    iconColor: '#F92672',
    category: 'Rent',
    categoryId: 'cat-10',
    date: '2024-01-01T00:00:00Z',
    amount: 2200.00,
    type: TransactionType.Expense,
    description: 'January rent',
    currency: 'USD',
  },
  {
    id: 'txn-22',
    merchant: 'Whole Foods',
    icon: 'shopping_cart',
    iconColor: '#66D9EF',
    category: 'Groceries',
    categoryId: 'cat-1',
    date: '2024-01-02T10:20:00Z',
    amount: 98.30,
    type: TransactionType.Expense,
    description: 'Groceries',
    currency: 'USD',
  },
  {
    id: 'txn-23',
    merchant: 'Shell',
    icon: 'directions_car',
    iconColor: '#E6DB74',
    category: 'Transportation',
    categoryId: 'cat-3',
    date: '2024-01-02T16:00:00Z',
    amount: 48.50,
    type: TransactionType.Expense,
    description: 'Gas',
    currency: 'USD',
  },
  // Previous month samples
  {
    id: 'txn-24',
    merchant: 'Best Buy',
    icon: 'shopping_bag',
    iconColor: '#FD971F',
    category: 'Shopping',
    categoryId: 'cat-5',
    date: '2023-12-28T14:30:00Z',
    amount: 599.99,
    type: TransactionType.Expense,
    description: 'New monitor',
    currency: 'USD',
  },
  {
    id: 'txn-25',
    merchant: 'Tech Corp Inc.',
    icon: 'payments',
    iconColor: '#A6E22E',
    category: 'Salary',
    categoryId: 'cat-8',
    date: '2023-12-31T00:00:00Z',
    amount: 4500.00,
    type: TransactionType.Income,
    description: 'Bi-weekly paycheck',
    currency: 'USD',
  },
  {
    id: 'txn-26',
    merchant: 'Mom\'s Birthday Gift',
    icon: 'card_giftcard',
    iconColor: '#F92672',
    category: 'Gifts',
    categoryId: 'cat-14',
    date: '2023-12-25T00:00:00Z',
    amount: 150.00,
    type: TransactionType.Expense,
    description: 'Birthday present',
    currency: 'USD',
  },
  {
    id: 'txn-27',
    merchant: 'Udemy',
    icon: 'school',
    iconColor: '#E6DB74',
    category: 'Education',
    categoryId: 'cat-15',
    date: '2023-12-20T00:00:00Z',
    amount: 89.99,
    type: TransactionType.Expense,
    description: 'React course',
    currency: 'USD',
  },
  {
    id: 'txn-28',
    merchant: 'CVS Pharmacy',
    icon: 'local_hospital',
    iconColor: '#A6E22E',
    category: 'Healthcare',
    categoryId: 'cat-6',
    date: '2023-12-18T11:30:00Z',
    amount: 45.20,
    type: TransactionType.Expense,
    description: 'Vitamins and supplements',
    currency: 'USD',
  },
  {
    id: 'txn-29',
    merchant: 'Olive Garden',
    icon: 'restaurant',
    iconColor: '#F92672',
    category: 'Dining Out',
    categoryId: 'cat-2',
    date: '2023-12-16T19:00:00Z',
    amount: 72.50,
    type: TransactionType.Expense,
    description: 'Dinner with friends',
    currency: 'USD',
  },
  {
    id: 'txn-30',
    merchant: 'Freelance Client',
    icon: 'work',
    iconColor: '#66D9EF',
    category: 'Freelance',
    categoryId: 'cat-9',
    date: '2023-12-15T00:00:00Z',
    amount: 1200.00,
    type: TransactionType.Income,
    description: 'Logo design project',
    currency: 'USD',
  },
];

// Category Budgets (15 budgets)
export const CATEGORY_BUDGETS: CategoryBudget[] = [
  {
    id: 'budget-1',
    category: 'Groceries',
    categoryId: 'cat-1',
    icon: 'shopping_cart',
    color: '#66D9EF',
    budgeted: 600.00,
    spent: 441.00,
    remaining: 159.00,
    percentageUsed: 73.5,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-2',
    category: 'Dining Out',
    categoryId: 'cat-2',
    icon: 'restaurant',
    color: '#F92672',
    budgeted: 400.00,
    spent: 385.95,
    remaining: 14.05,
    percentageUsed: 96.5,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: true,
  },
  {
    id: 'budget-3',
    category: 'Transportation',
    categoryId: 'cat-3',
    icon: 'directions_car',
    color: '#E6DB74',
    budgeted: 300.00,
    spent: 125.60,
    remaining: 174.40,
    percentageUsed: 41.9,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-4',
    category: 'Entertainment',
    categoryId: 'cat-4',
    icon: 'movie',
    color: '#AE81FF',
    budgeted: 200.00,
    spent: 38.50,
    remaining: 161.50,
    percentageUsed: 19.3,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-5',
    category: 'Shopping',
    categoryId: 'cat-5',
    icon: 'shopping_bag',
    color: '#FD971F',
    budgeted: 500.00,
    spent: 1166.98,
    remaining: -666.98,
    percentageUsed: 233.4,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: true,
    isNearLimit: true,
  },
  {
    id: 'budget-6',
    category: 'Healthcare',
    categoryId: 'cat-6',
    icon: 'local_hospital',
    color: '#A6E22E',
    budgeted: 150.00,
    spent: 77.70,
    remaining: 72.30,
    percentageUsed: 51.8,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-7',
    category: 'Utilities',
    categoryId: 'cat-7',
    icon: 'bolt',
    color: '#75715E',
    budgeted: 200.00,
    spent: 142.30,
    remaining: 57.70,
    percentageUsed: 71.2,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-8',
    category: 'Rent',
    categoryId: 'cat-10',
    icon: 'home',
    color: '#F92672',
    budgeted: 2200.00,
    spent: 2200.00,
    remaining: 0,
    percentageUsed: 100,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: true,
  },
  {
    id: 'budget-9',
    category: 'Subscriptions',
    categoryId: 'cat-11',
    icon: 'subscriptions',
    color: '#AE81FF',
    budgeted: 100.00,
    spent: 26.98,
    remaining: 73.02,
    percentageUsed: 27.0,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-10',
    category: 'Fitness',
    categoryId: 'cat-12',
    icon: 'fitness_center',
    color: '#A6E22E',
    budgeted: 50.00,
    spent: 39.99,
    remaining: 10.01,
    percentageUsed: 80.0,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: true,
  },
  {
    id: 'budget-11',
    category: 'Travel',
    categoryId: 'cat-13',
    icon: 'flight',
    color: '#66D9EF',
    budgeted: 500.00,
    spent: 420.00,
    remaining: 80.00,
    percentageUsed: 84.0,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: true,
  },
  {
    id: 'budget-12',
    category: 'Gifts',
    categoryId: 'cat-14',
    icon: 'card_giftcard',
    color: '#F92672',
    budgeted: 200.00,
    spent: 150.00,
    remaining: 50.00,
    percentageUsed: 75.0,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-13',
    category: 'Education',
    categoryId: 'cat-15',
    icon: 'school',
    color: '#E6DB74',
    budgeted: 150.00,
    spent: 89.99,
    remaining: 60.01,
    percentageUsed: 60.0,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-14',
    category: 'All Categories',
    categoryId: 'global',
    icon: 'account_balance_wallet',
    color: '#F92672',
    budgeted: 7000.00,
    spent: 5304.00,
    remaining: 1696.00,
    percentageUsed: 75.8,
    period: BudgetPeriod.Monthly,
    warningThreshold: 85,
    isOverBudget: false,
    isNearLimit: false,
  },
  {
    id: 'budget-15',
    category: 'Discretionary',
    categoryId: 'cat-misc',
    icon: 'wallet',
    color: '#AE81FF',
    budgeted: 300.00,
    spent: 125.50,
    remaining: 174.50,
    percentageUsed: 41.8,
    period: BudgetPeriod.Monthly,
    warningThreshold: 80,
    isOverBudget: false,
    isNearLimit: false,
  },
];

// Monthly Analytics Data
export const MONTHLY_ANALYTICS: MonthlyAnalytics = {
  periodStart: '2024-01-01T00:00:00Z',
  periodEnd: '2024-01-31T23:59:59Z',
  totalSpending: 5304.00,
  totalIncome: 6050.00,
  netSavings: 746.00,
  budgetAdherence: 75.8, // percentage
  categoryBreakdown: [
    {
      category: 'Rent',
      categoryId: 'cat-10',
      amount: 2200.00,
      percentage: 41.5,
      color: '#F92672',
      icon: 'home',
    },
    {
      category: 'Shopping',
      categoryId: 'cat-5',
      amount: 1166.98,
      percentage: 22.0,
      color: '#FD971F',
      icon: 'shopping_bag',
    },
    {
      category: 'Groceries',
      categoryId: 'cat-1',
      amount: 441.00,
      percentage: 8.3,
      color: '#66D9EF',
      icon: 'shopping_cart',
    },
    {
      category: 'Travel',
      categoryId: 'cat-13',
      amount: 420.00,
      percentage: 7.9,
      color: '#66D9EF',
      icon: 'flight',
    },
    {
      category: 'Dining Out',
      categoryId: 'cat-2',
      amount: 385.95,
      percentage: 7.3,
      color: '#F92672',
      icon: 'restaurant',
    },
    {
      category: 'Gifts',
      categoryId: 'cat-14',
      amount: 150.00,
      percentage: 2.8,
      color: '#F92672',
      icon: 'card_giftcard',
    },
    {
      category: 'Utilities',
      categoryId: 'cat-7',
      amount: 142.30,
      percentage: 2.7,
      color: '#75715E',
      icon: 'bolt',
    },
    {
      category: 'Transportation',
      categoryId: 'cat-3',
      amount: 125.60,
      percentage: 2.4,
      color: '#E6DB74',
      icon: 'directions_car',
    },
    {
      category: 'Education',
      categoryId: 'cat-15',
      amount: 89.99,
      percentage: 1.7,
      color: '#E6DB74',
      icon: 'school',
    },
    {
      category: 'Healthcare',
      categoryId: 'cat-6',
      amount: 77.70,
      percentage: 1.5,
      color: '#A6E22E',
      icon: 'local_hospital',
    },
    {
      category: 'Fitness',
      categoryId: 'cat-12',
      amount: 39.99,
      percentage: 0.8,
      color: '#A6E22E',
      icon: 'fitness_center',
    },
    {
      category: 'Entertainment',
      categoryId: 'cat-4',
      amount: 38.50,
      percentage: 0.7,
      color: '#AE81FF',
      icon: 'movie',
    },
    {
      category: 'Subscriptions',
      categoryId: 'cat-11',
      amount: 26.98,
      percentage: 0.5,
      color: '#AE81FF',
      icon: 'subscriptions',
    },
  ],
  topCategories: [
    {
      category: 'Rent',
      categoryId: 'cat-10',
      amount: 2200.00,
      percentage: 41.5,
      color: '#F92672',
      icon: 'home',
    },
    {
      category: 'Shopping',
      categoryId: 'cat-5',
      amount: 1166.98,
      percentage: 22.0,
      color: '#FD971F',
      icon: 'shopping_bag',
    },
    {
      category: 'Groceries',
      categoryId: 'cat-1',
      amount: 441.00,
      percentage: 8.3,
      color: '#66D9EF',
      icon: 'shopping_cart',
    },
    {
      category: 'Travel',
      categoryId: 'cat-13',
      amount: 420.00,
      percentage: 7.9,
      color: '#66D9EF',
      icon: 'flight',
    },
    {
      category: 'Dining Out',
      categoryId: 'cat-2',
      amount: 385.95,
      percentage: 7.3,
      color: '#F92672',
      icon: 'restaurant',
    },
  ],
  spendingTrend: [
    { week: 1, actual: 895.50, projected: 1000.00 },
    { week: 2, actual: 1245.80, projected: 1000.00 },
    { week: 3, actual: 2980.00, projected: 1000.00 },
    { week: 4, actual: 182.70, projected: 1000.00 },
  ],
};
